feat(upload): Upload info
chiflix/splayerx pull request #1172
Opened 2019-11-22 06:15 UTC by YuRiJinX

2019-11-22 08:07 UTC, ipy commented on src/renderer/main.ts
> +          electronVersion: process.versions.electron,
加一下 electron hash: `splayerx.getVersionHash().trim()`

2019-11-22 08:14 UTC, ipy requested changes

2019-11-22 08:14 UTC, ipy commented on src/renderer/main.ts
> +            secondarySubtitle: this.list.find((val: ISubtitleControlListItem) => val.id === this.secondarySubtitleId),
<img width="388" alt="图片" src="https://user-images.githubusercontent.com/2088040/69409001-1258c980-0d43-11ea-8e52-26dc75515571.png">
貌似要传所有字幕信息

2019-11-22 10:14 UTC, ipy requested changes

2019-11-22 10:14 UTC, ipy commented on src/renderer/main.ts
> +        const crashReportPath = path.join(app.getPath('temp'), `${app.getName()} Crashes/completed`);
<img width="950" alt="图片" src="https://user-images.githubusercontent.com/2088040/69417500-bfd3d900-0d53-11ea-9d27-8009ebd19937.png">
crash 目录路径参见这段逻辑
然后要判断一下，mas 版本不执行

2019-11-22 10:17 UTC, ipy commented on src/main/menu/Menu.ts
>      if (!process.mas) {
然后这里的mas判断去掉，mas不产生crash report，但是手动提交应该还是可以的

2019-11-22 10:20 UTC, ipy commented on src/renderer/main.ts
> +            parsefile.save().then(() => {
文件挂到 report 上去

2019-11-22 10:24 UTC, YuRiJinX commented on src/renderer/main.ts
> +        const crashReportPath = path.join(app.getPath('temp'), `${app.getName()} Crashes/completed`);
说起来我为啥没看到crashReporter有这个getCrashesDirectory的方法。。
然后mas版是不上传dmpfile还是直接没有这个菜单项了？

2019-11-22 10:25 UTC, YuRiJinX commented on src/main/menu/Menu.ts
>      if (!process.mas) {
ok

2019-11-23 01:36 UTC, ipy commented on src/renderer/main.ts
> +        const crashReportPath = path.join(app.getPath('temp'), `${app.getName()} Crashes/completed`);
嗯，mas 下 crashReporter 被禁用了

2019-11-25 06:49 UTC, ipy approved these changes

2019-11-25 06:53 UTC, ipy approved these changes

2019-11-25 06:53 UTC, merged