fix(browsingview): fix download in Windows
chiflix/splayerx pull request #1211
Opened 2019-12-17 04:37 UTC by Pat1enceLos

- add youtube-dl sha256 verify
- check Visual C++ 2010 runtimes in Windows
- improve style when download limited

2019-12-17 06:55 UTC, ipy requested changes

2019-12-17 06:55 UTC, ipy commented on src/renderer/components/BrowsingView.vue
> +        } else if (!this.isDarwin && !(await checkVcRedistributablePackage())) {
应该检查是Windows而不是非mac

2019-12-17 09:19 UTC, ipy submitted a review, later dismissed

2019-12-18 01:59 UTC, ipy commented on yarn.lock
> +  version "1.4.1"
是删了 yarn.lock 重新安装的？这个版本的 configcat 好像有问题

2019-12-18 02:56 UTC, Pat1enceLos commented on yarn.lock
> +  version "1.4.1"
更新了youtube-dl的库，当时就删了yarn.lock重新装的

2019-12-18 04:23 UTC, ipy approved these changes

2019-12-18 04:33 UTC, merged