perf(ui): improve performance on resizing
chiflix/splayerx pull request #165
Opened 2018-09-01 11:51 UTC by ipy

解决了调整大小时卡顿的问题。

注释掉了一段代码和对应的测试，这段代码的意图应该在是在窗口获得焦点时，如果鼠标在窗口内就开始播放。不过：
* 代码有点问题并没有正常工作
* 开始播放是个比较危险的动作并不适合在窗口聚焦时不经过用户就自动开始
这个需要确认下 @huzhenghui37

2018-09-01 12:05 UTC, huzhenghui37 commented
这个功能我知道，是梁以昌同学以前写的，当时是希望播放窗口没有焦点时点击播放窗口获得焦点，如果处于暂停播放状态，则直接开始播放，如果是正在播放，则只是获得焦点。没想到会影响性能。

2018-09-01 12:08 UTC, huzhenghui37 commented
果然快了很多，哈哈。

2018-09-01 12:11 UTC, ipy commented
我表达有误，这个功能跟性能没关系，是由于这个功能没通过测试，所以看了下。现在这个功能有点问题，并没有实现暂停时开始播放。而且个人觉得这个功能本身并不是特别合适，所以找你确认下。如果确定要做我就把这个 bug 修一下，不做的话就把注释掉的代码删掉。 @huzhenghui37

2018-09-01 12:13 UTC, tomasen requested changes

2018-09-01 12:13 UTC, tomasen commented on src/renderer/components/LandingView.vue
> +    if (process.platform !== 'darwin') {
这里为什么换成这种写法？是确定Linux也不支持drag么？

2018-09-01 12:13 UTC, tomasen commented on src/renderer/components/LandingView/Playlist.vue
> +      const VALID_EXTENSION = ['3g2', '3gp', '3gp2', '3gpp', 'amv', 'asf', 'avi', 'bik', 'bin', 'crf', 'divx', 'drc', 'dv', 'dvr-ms', 'evo', 'f4v', 'flv', 'gvi', 'gxf', 'iso', 'm1v', 'm2v', 'm2t', 'm
有来源么？有些担心这里会不会不全

2018-09-01 12:13 UTC, tomasen commented on src/renderer/components/PlayingView.vue
> +        // // TODO: move isPlaying to global state to prevent nested refs
这里的功能应该如eric所说，还是需要的。

2018-09-01 12:13 UTC, tomasen commented on test/unit/specs/PlayingView.spec.js
> +    // const win = vue.mainWindow;
如前

2018-09-01 12:13 UTC, huzhenghui37 commented
注释掉吧，貌似也不妥。刚刚试了一下这个PR版本，缩放窗口确实快了不少。

2018-09-01 12:23 UTC, ipy commented on src/renderer/components/LandingView.vue
> +    if (process.platform !== 'darwin') {
嗯，亲测不可用...

2018-09-01 12:25 UTC, ipy commented on src/renderer/components/LandingView/Playlist.vue
> +      const VALID_EXTENSION = ['3g2', '3gp', '3gp2', '3gpp', 'amv', 'asf', 'avi', 'bik', 'bin', 'crf', 'divx', 'drc', 'dv', 'dvr-ms', 'evo', 'f4v', 'flv', 'gvi', 'gxf', 'iso', 'm1v', 'm2v', 'm2t', 'm
Copied from VLC. 只是临时解决一下，原来用空数组在 Mac 上没问题，但是其他平台上无法选择文件，必须要传入一些扩展名。

2018-09-01 12:26 UTC, ipy commented on src/renderer/components/PlayingView.vue
> +        // // TODO: move isPlaying to global state to prevent nested refs
👌

2018-09-01 12:56 UTC, tomasen commented on src/renderer/components/LandingView/Playlist.vue
> +      const VALID_EXTENSION = ['3g2', '3gp', '3gp2', '3gpp', 'amv', 'asf', 'avi', 'bik', 'bin', 'crf', 'divx', 'drc', 'dv', 'dvr-ms', 'evo', 'f4v', 'flv', 'gvi', 'gxf', 'iso', 'm1v', 'm2v', 'm2t', 'm
了解了

2018-09-01 12:57 UTC, tomasen commented on src/renderer/components/PlayingView.vue
> +        // // TODO: move isPlaying to global state to prevent nested refs
确定不能用就删掉吧。也不要注释了

2018-09-01 12:57 UTC, tomasen commented on test/unit/specs/PlayingView.spec.js
> +    // const win = vue.mainWindow;
确定不能用就删掉吧。也不要注释了

2018-09-01 13:03 UTC, tomasen commented on src/renderer/components/PlayingView.vue
> +        // // TODO: move isPlaying to global state to prevent nested refs
或者/* */ 注释中解释清楚为什么

2018-09-01 23:13 UTC, ipy commented
调整了下，原先 Cmd+Tab 聚焦的时如果鼠标在窗口内也会开始播放；现在必须通过鼠标点击聚焦才会播放。

2018-09-02 02:30 UTC, tomasen approved these changes

2018-09-02 02:30 UTC, merged