开发任务：窗口最大化（非全屏）/ 恢复原始大小操作 完成
chiflix/splayerx pull request #193
Opened 2018-09-20 05:37 UTC by Delbra

开发任务：窗口最大化（非全屏）/ 恢复原始大小操作 完成
在titlebar加了双击事件监听，使用electron的api currentWindow.unmaximize()喝currentWindow.maximize();实现最大化和恢复原始大小
在原有监听handleMouseOver()和handleMouseOut()上增加了键盘输入监听来实现Option+鼠标hover切换图标的功能，并复用handleDoubleClick()来实现最大化和恢复原始大小功能

2018-09-20 23:11 UTC, ipy requested changes

2018-09-20 23:11 UTC, ipy commented on src/renderer/components/LandingView/Playlist.vue
> +      // document.querySelector('.item').style.transition = '';
注释不需要推上来，直接删掉就好
如果是有必要保留的话，加下注释说明一下原因

2018-09-21 03:21 UTC, huzhenghui37 commented on src/renderer/components/LandingView/Playlist.vue
> +      // document.querySelector('.item').style.transition = '';
这个PR还是有些小问题。

2018-09-21 08:17 UTC, YuRiJinX commented on src/renderer/components/Titlebar.vue
> +      const windowMaxSize = this.$electron.screen.getPrimaryDisplay().workAreaSize;// eslint-disable-line
这段要对多显示器做支持
```js
      const [windowX, windowY] = currentWindow.getPosition();
      const windowPosition = { x: windowX, y: windowY };
      const currentDisplay = this.$electron.screen.getDisplayNearestPoint(windowPosition);
```

2018-10-13 01:21 UTC, closed without merging