VolumeBar
chiflix/splayerx pull request #2
Opened 2018-04-28 07:38 UTC by YuRiJinX

静音图标想用一个对象v-bind到img的src来实现，但地址识别不出

2018-04-28 10:19 UTC, tomasen commented on src/renderer/components/PlayingView/VolumeControl.vue
> +        <!-- src需要绑定srcOfVolumeButtonImage对象以改变图标，但地址无法读出 -->
这个注释是什么意思，看不懂

2018-04-28 10:21 UTC, tomasen requested changes
关于srcOfVolumeButtonImage有问题

2018-04-28 10:21 UTC, tomasen commented on src/renderer/components/PlayingView/VolumeControl.vue
> +      srcOfVolumeButtonImage: '~@/assets/icon-volume.svg',
这个没用上？
没用上就不要放在代码中了，如果应该用上的话，微信讨论下。

2018-04-30 10:24 UTC, YuRiJinX commented on src/renderer/components/PlayingView/VolumeControl.vue
> +        <!-- src需要绑定srcOfVolumeButtonImage对象以改变图标，但地址无法读出 -->
本来的那一行是要写成v-bind:src="srcOfVolumeButtonImage",然后想通过改这个对象的参数来换图标，但是写了之后图标就读不出来

2018-04-30 10:25 UTC, YuRiJinX commented on src/renderer/components/PlayingView/VolumeControl.vue
> +        <!-- src需要绑定srcOfVolumeButtonImage对象以改变图标，但地址无法读出 -->
不知道是什么问题

2018-05-10 06:16 UTC, merged