feat(logs): use winston to store log and source-map-support to trace error stack
chiflix/splayerx pull request #226
Opened 2018-10-26 06:33 UTC by Pat1enceLos

- new a folder named 'logs' 

- all log file name format depend on date just like "2018-10-26.log"

- all records follow the format "Time - Type : Message" just like "2018-10-26T05:57:44.836Z - info: launching: SPlayerX 0.0.3"

- logs will record the errorstack when type is error

- may improve log content and details in the future

2018-10-26 23:52 UTC, ipy commented on src/renderer/helpers/infoDB.js
> +import addLog from './index';
logger 相关最好单独放一个文件，避免文件互相 import 的混乱

2018-10-26 23:58 UTC, ipy commented on src/renderer/helpers/index.js
> +      const logger = winston.createLogger({
logger 可以尝试复用，不用每次都创建一个

2018-10-28 07:09 UTC, ipy commented on src/renderer/helpers/index.js
> +    addLog(level, message) {
开发模式下可以也在控制台输出来，方便调试

2018-10-28 07:13 UTC, ipy requested changes

2018-10-28 07:13 UTC, ipy commented on src/renderer/main.js
> +require('source-map-support').install();
source-map-support 不生效的原因应该是它只区分了 node 和 browser 环境，electron 环境没有特别处理导致获取的源代码路径不对。
要处理的话可以调整下它的源码，不过我觉得没有必要在播放器代码里处理这个，开发环境可以用 devtool；生产环境可以收集原始日志回来之后再分析，不用把 sourcemap 暴露给用户端

2018-10-28 07:15 UTC, ipy commented
错误信息也可以用[Sentry](https://sentry.io/)这样的云服务收集，采集起来方便一点

2018-10-29 02:55 UTC, Pat1enceLos commented on src/renderer/main.js
> +require('source-map-support').install();
后来发现打包生成的sourcemap也有问题，之前用的babili 0.1.2,不能用#source-map，降到0.1.1后就可以了，现在应该是能定位到行的

2018-10-29 03:39 UTC, ipy commented
这个 pr 先合掉，提的几点可以后面优化一下 @Pat1enceLos

2018-10-29 03:40 UTC, merged