feat(playlist): new playlist
chiflix/splayerx pull request #236
Opened 2018-11-09 10:58 UTC by YuRiJinX

## Playlist 
- new component
- TODO: 
- - it may cause performance issue
- - need more tests
## Vuex
- add some Playlist related getters
## VideoCanvas
- get a cover while video first opened
- cover will be used for landingview
## Main Process
- an event for calling snapShot api

2018-11-15 13:22 UTC, ipy requested changes

2018-11-15 13:22 UTC, ipy commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +        marginTop: winWidth > 1355 ?  `${(winWidth / 1355) * 53}px` : '53px',
这个判断可以抽一个通用方法出来

2018-11-15 13:22 UTC, ipy commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +import { Video as videoAction } from '@/store/actionTypes.js';
之前定的统一不写 .js

2018-11-15 13:22 UTC, ipy commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +    // if you wanna know the meanings of wABC, please look up the product doc
贴一下文档地址吧
看了下文档，里面好像并没有直接命名，所以还是要简单解释一下表示什么（能用命名表达更好）
每个方法里常量都是一样的话可以写在外面统一维护

2018-11-15 13:22 UTC, ipy commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +      } else if (this.winWidth === 720) {
这个好像可以并到下面那个判断？

2018-11-15 13:22 UTC, ipy commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +        width = ((((this.winWidth - A) - C) + B) / this.thumbnailNumber) - B;
看样子也可以用 media query + css calc 表达出来，性能会不会好一点就不清楚了（更看不懂是肯定的🤣）

2018-11-15 13:22 UTC, ipy commented on src/renderer/components/PlayingView/RecentPlaylistItem.vue
> +      fs.readFile(`${imgPath}.png`, 'base64', (err, data) => {
今早提到`fs.readFile`是跨进程的，有可能导致性能问题。`src`其实可以直接使用 file url，要转 base64 存数据库的话可以再异步来做

2018-11-15 13:22 UTC, ipy commented on src/renderer/store/modules/Video.js
> +  duration: NaN,
这个调整能说明一下吗

2018-11-15 13:26 UTC, YuRiJinX commented on src/renderer/store/modules/Video.js
> +  duration: NaN,
如果没这个调整在打开任何数据库中有记录上次播放时间的视频会卡住不动或闪退

2018-11-15 13:36 UTC, YuRiJinX commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +    // if you wanna know the meanings of wABC, please look up the product doc
这几个常量只有在这里用我觉得不太需要放在外面来维护

2018-11-15 13:40 UTC, YuRiJinX commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +        width = ((((this.winWidth - A) - C) + B) / this.thumbnailNumber) - B;
因为这两个计算属性需要被其他地方调用所以要写在js里

2018-11-15 13:40 UTC, ipy commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +    // if you wanna know the meanings of wABC, please look up the product doc
嗯，简单说明下吧，不然其他人看这段代码的话还得翻文档，文档上也没有标注

2018-11-15 15:56 UTC, YuRiJinX commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +        marginTop: winWidth > 1355 ?  `${(winWidth / 1355) * 53}px` : '53px',
这个ok了

2018-11-15 15:56 UTC, YuRiJinX commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +import { Video as videoAction } from '@/store/actionTypes.js';
这个ok了

2018-11-15 15:57 UTC, YuRiJinX commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +      } else if (this.winWidth === 720) {
这个ok了

2018-11-15 16:02 UTC, YuRiJinX commented on src/renderer/components/PlayingView/RecentPlaylist.vue
> +    // if you wanna know the meanings of wABC, please look up the product doc
这个ok了

2018-11-15 16:07 UTC, YuRiJinX commented on src/renderer/components/PlayingView/RecentPlaylistItem.vue
> +      fs.readFile(`${imgPath}.png`, 'base64', (err, data) => {
这个ok了

2018-11-16 03:11 UTC, ipy approved these changes

2018-11-16 03:11 UTC, merged