Fix(ui) miscenllaneous bugs
chiflix/splayerx pull request #247
Opened 2018-11-16 11:43 UTC by YvonTre

- Tempoary commit, straightToTheYellowDragon is not finished yet.
- Fix TheProgressBar height problem.
- Fix getAwayImStarting button color flickering.

2018-11-17 00:42 UTC, ipy commented on src/renderer/components/PlayingView/TheProgressBar.vue
> +      let opacity;
没有默认值的话，不是会出现 undefined 的情况？

2018-11-20 06:34 UTC, YvonTre commented on src/renderer/components/PlayingView/TheProgressBar.vue
> +      let opacity;
现在把默认值加回去了。

2018-11-20 08:05 UTC, ipy requested changes

2018-11-20 08:05 UTC, ipy commented on src/main/index.js
> +    const vidRegex = new RegExp('^(.3g2|.3gp|.3gp2|.3gpp|.amv|.asf|.avi|.bik|.bin|.crf|.divx|.drc|.dv|.dvr-ms|.evo|.f4v|.flv|.gvi|.gxf|.iso|.m1v|.m2v|.m2t|.m2ts|.m4v|.mkv|.mov|.mp2|.mp2v|.mp4|.mp4v|.
正则的`.`可以匹配任意字符，需要转义

2018-11-20 08:05 UTC, ipy commented on src/renderer/components/PlayingView/InfoCard.vue
> +      validator: value => value > 0 && !Number.isNaN(value),
什么情况下 `value > 0` is时 `Number.isNaN(value)` 为真呢？

2018-11-20 08:05 UTC, ipy commented on src/renderer/components/PlayingView/VideoCanvas.vue
> +      :currentAudioTrackId="currentAudioTrackId.toString()"
这里有没有可能出现空引用？

2018-11-20 08:05 UTC, ipy commented on src/renderer/main.js
> +      const vidRegex = new RegExp('^(.3g2|.3gp|.3gp2|.3gpp|.amv|.asf|.avi|.bik|.bin|.crf|.divx|.drc|.dv|.dvr-ms|.evo|.f4v|.flv|.gvi|.gxf|.iso|.m1v|.m2v|.m2t|.m2ts|.m4v|.mkv|.mov|.mp2|.mp2v|.mp4|.mp4v
同前

2018-11-20 08:26 UTC, YvonTre commented on src/main/index.js
> +    const vidRegex = new RegExp('^(.3g2|.3gp|.3gp2|.3gpp|.amv|.asf|.avi|.bik|.bin|.crf|.divx|.drc|.dv|.dvr-ms|.evo|.f4v|.flv|.gvi|.gxf|.iso|.m1v|.m2v|.m2t|.m2ts|.m4v|.mkv|.mov|.mp2|.mp2v|.mp4|.mp4v|.
请问哪里需要转义字符呢，在console里试过了并不是可以匹配任意字符的。
现在把`^`删掉，因为不是完全匹配后缀名。

2018-11-20 08:26 UTC, YvonTre commented on src/renderer/components/PlayingView/InfoCard.vue
> +      validator: value => value > 0 && !Number.isNaN(value),
调整回`value > 0`了。

2018-11-20 08:29 UTC, YvonTre commented on src/renderer/components/PlayingView/VideoCanvas.vue
> +      :currentAudioTrackId="currentAudioTrackId.toString()"
`currentAudioTrack`是vuex的getter，有默认返回值-1的，应该不会出现空引用。

2018-11-20 08:39 UTC, ipy commented on src/main/index.js
> +    const vidRegex = new RegExp('^(.3g2|.3gp|.3gp2|.3gpp|.amv|.asf|.avi|.bik|.bin|.crf|.divx|.drc|.dv|.dvr-ms|.evo|.f4v|.flv|.gvi|.gxf|.iso|.m1v|.m2v|.m2t|.m2ts|.m4v|.mkv|.mov|.mp2|.mp2v|.mp4|.mp4v|.
![default](https://user-images.githubusercontent.com/2088040/48761105-c9f76d80-ece2-11e8-99fb-37a3059bf69e.png)

2018-11-20 09:11 UTC, YvonTre commented on src/main/index.js
> +    const vidRegex = new RegExp('^(.3g2|.3gp|.3gp2|.3gpp|.amv|.asf|.avi|.bik|.bin|.crf|.divx|.drc|.dv|.dvr-ms|.evo|.f4v|.flv|.gvi|.gxf|.iso|.m1v|.m2v|.m2t|.m2ts|.m4v|.mkv|.mov|.mp2|.mp2v|.mp4|.mp4v|.
好的，现在改成这样了。
`const vidRegex = new RegExp('\\.(3g2|3gp|3gp2|3gpp|amv|asf|avi|bik|bin|crf|divx|drc|dv|dvr-ms|evo|f4v|flv|gvi|gxf|iso|m1v|m2v|m2t|m2ts|m4v|mkv|mov|mp2|mp2v|mp4|mp4v|mpe|mpeg|mpeg1|mpeg2|mpeg4|mpg|mpv2|mts|mtv|mxf|mxg|nsv|nuv|ogg|ogm|ogv|ogx|ps|rec|rm|rmvb|rpl|thp|tod|tp|ts|tts|txd|vob|vro|webm|wm|wmv|wtv|xesc)$');`

2018-11-20 09:26 UTC, ipy approved these changes

2018-11-20 09:26 UTC, merged