Refactor(input):seperate input info
chiflix/splayerx pull request #306
Opened 2018-12-13 13:51 UTC by YvonTre

2018-12-13 14:01 UTC, ipy commented
这个 pr 带了哪些 feature?

2018-12-13 15:03 UTC, YvonTre commented
为接下来移除所有的eventInfo作准备

2018-12-14 01:32 UTC, ipy commented
如果只是代码重构可能要稍晚点再合,临近发版要控制下风险

2018-12-15 03:15 UTC, tomasen requested changes
travis ci 报错。 找不到 Cannot find module '@/components/PlayingView/TheVideoController'

2018-12-15 08:47 UTC, tomasen requested changes

2018-12-15 08:47 UTC, tomasen commented on test/unit/specs/TheVideoController.spec.js
> +import TheVideoController from '@/components/PlayingView/TheVideoController';
spec 里面应该不能这样 import vue
如果测 vue ，要参考 vue-test-utils

2018-12-24 03:35 UTC, closed without merging