Optimized present time in video
chiflix/splayerx pull request #314
Opened 2018-12-14 09:17 UTC by ymmuse

Use a global variable to record the present time.

2018-12-14 09:23 UTC, tomasen requested changes
冲突求修

2018-12-14 12:57 UTC, ipy commented on src/renderer/store/modules/Video.js
>    currentTime: state => state.currentTime,
这里的不用的话先删掉吧？

2018-12-14 13:16 UTC, ymmuse commented on src/renderer/store/modules/Video.js
>    currentTime: state => state.currentTime,
nextVideoPreviewTime在用

2018-12-14 13:23 UTC, ipy commented on src/renderer/store/modules/Video.js
>    currentTime: state => state.currentTime,
在哪里更新的呢

2018-12-14 13:24 UTC, YuRiJinX commented on src/renderer/store/modules/Video.js
>    currentTime: state => state.currentTime,
不更新，只是用来触发next卡片的出现的

2018-12-15 08:46 UTC, tomasen approved these changes

2018-12-15 08:46 UTC, merged