fix(videocanvas): change implement of saving infos before window closed
chiflix/splayerx pull request #389
Opened 2019-01-09 13:52 UTC by YuRiJinX

2019-01-09 23:16 UTC, ipy requested changes

2019-01-09 23:16 UTC, ipy commented on src/renderer/components/PlayingView/VideoCanvas.vue
> +        this.saveScreenshot(this.originSrc).then(this.saveSubtitleStyle()).then(() => {
`saveSubtitleStyle()`是不是多打了个括号？
`.catch`应该也要处理一下，避免保存失败窗口关不掉

2019-01-10 07:02 UTC, YuRiJinX commented on src/renderer/components/PlayingView/VideoCanvas.vue
> +        this.saveScreenshot(this.originSrc).then(this.saveSubtitleStyle()).then(() => {
saveSubtitleStyle好像没多打，其他ok了

2019-01-10 09:31 UTC, ipy approved these changes

2019-01-10 09:31 UTC, merged