Refactor(subtitle) add tests and refactor
chiflix/splayerx pull request #466
Opened 2019-02-12 08:33 UTC by YvonTre

- Refactor subtitle helpers.
- Add unit tests for and refactor following functions:
  - `SubtitleManager`
    - `refreshSubtitles`
    - `getLocalSubtitlesList`
    - `getOnlineSubtitlesList`
    - `getEmbeddedSubtitlesList`
  - `@/helpers/subtitle/searchers`
    - `searchforLocalList`
    - `fetchOnlineList`
    - `retrieveEmbeddedList`
- Implement stubbing dependencies functionality with `babel-plugin-rewire`.

2019-02-12 13:50 UTC, ipy requested changes

2019-02-12 13:50 UTC, ipy commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +      return searchforLocalList(videoSrc, SubtitleLoader.supportedFormats).catch(() => []);
照说应该是 `searchFor`... 或者可以用 find

2019-02-12 13:50 UTC, ipy commented on src/renderer/helpers/subtitle/index.js
> +export * from './searchers';
为什么不直接把代码写在 index.js 里呢？

2019-02-12 13:50 UTC, ipy commented on src/renderer/helpers/subtitle/searchers.js
> +    const extensionRegex = new RegExp(`\\.(${validExtensions.join('|')})$`);
没有忽略大小写？

2019-02-13 07:10 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +      return searchforLocalList(videoSrc, SubtitleLoader.supportedFormats).catch(() => []);
改成`searchFor`了。

2019-02-13 07:11 UTC, YvonTre commented on src/renderer/helpers/subtitle/index.js
> +export * from './searchers';
因为以后会加一些其他的模块在subtitle文件夹下，会导致index.js变得很大。

2019-02-13 07:44 UTC, YvonTre commented on src/renderer/helpers/subtitle/searchers.js
> +    const extensionRegex = new RegExp(`\\.(${validExtensions.join('|')})$`);
添加了忽略大小写和相应的测试

2019-02-13 08:26 UTC, ipy approved these changes

2019-02-13 08:26 UTC, merged