refactor(parseName): use reg replace third libs to parseName
chiflix/splayerx pull request #478
Opened 2019-02-19 03:52 UTC by townmi

- [x] remove third libs (anitomyscript, guessit-wrapper)
- [x] add parseNameFromPath in helpers use reg match

2019-02-20 02:43 UTC, ipy commented on src/renderer/helpers/path.js
> +  const ls = [null, null]; // [se, ep]
这里 `ls` 变量可以不用，直接用返回对象就行；`l` 变量可以不用，数组后直接 .forEach 就行；`a` rest参数可以不用，直接用 $0, $1, $2 可读性更强。最主要问题是这几个短变量名完全无法 get 到含义。

2019-02-20 02:43 UTC, ipy commented on src/renderer/helpers/path.js
> +const SEREG = /(\.s[e]?(\d+)|(\d+)季|([零一二三四五六七八九十百千]+)季)/i;
应该不是所有都是 `.` 开头的，例如`Grey's Anatomy - s01e03.mp4`

2019-02-20 02:43 UTC, ipy commented on src/renderer/helpers/path.js
> +const SEREG = /(\.s[e]?(\d+)|(\d+)季|([零一二三四五六七八九十百千]+)季)/i;
中文是否可以不省略“第”字？正常中文不带第字读不通，而且假如剧名里有“四季”之类的就会匹配错误

2019-02-20 02:43 UTC, ipy commented on src/renderer/helpers/path.js
> +  l.forEach((r, i) => {
这里用 `forEach` 使用同一个方法处理的话，要求 season 和 episode 的正则格式必须完全一致，可扩展性不太强。

个人一些想法：
目前看下来只判断了固定的几种模式，那不如就按照这几中模式来匹配，而且英文目前的例子里貌似没有只有 season 或只有 episode 的，可以不用分开匹配，可读性和精确性会高不少。
类似这样：
/se(\d+)[\.-]?ep(\d+)/i
/s(\d+)[\.-]?e(\d+)/i
/第([零一二三四五六七八九十百千]+|\d+)季/
/第([零一二三四五六七八九十百千]+|\d+)集/

2019-02-20 02:52 UTC, ipy commented
guessit 的代码是开源的，如果要做复杂匹配的话可以参考
https://github.com/guessit-io/guessit/blob/develop/guessit/rules/properties/episodes.py

2019-02-20 03:49 UTC, townmi commented on src/renderer/helpers/path.js
> +const SEREG = /(\.s[e]?(\d+)|(\d+)季|([零一二三四五六七八九十百千]+)季)/i;
那就再加个空格开头的条件。

2019-02-20 03:50 UTC, townmi commented on src/renderer/helpers/path.js
> +const SEREG = /(\.s[e]?(\d+)|(\d+)季|([零一二三四五六七八九十百千]+)季)/i;
主要考虑到测试案例` 01集` 这样的情况。

2019-02-20 04:01 UTC, townmi commented on src/renderer/helpers/path.js
> +  l.forEach((r, i) => {
有可能只有episode，分开主要是考虑season 和 episode 匹配的子项基本一致，合起来子项条件太多，容易乱。

2019-02-20 04:02 UTC, townmi commented on src/renderer/helpers/path.js
> +  const ls = [null, null]; // [se, ep]
嗯，我优化下变量和参数。

2019-02-20 04:28 UTC, ipy commented on src/renderer/helpers/path.js
> +const SEREG = /(\.s[e]?(\d+)|(\d+)季|([零一二三四五六七八九十百千]+)季)/i;
扫了眼还有 `7o9-ancient-aliens-s01e01-720p-bluray-x264.mkv`

2019-02-20 04:29 UTC, ipy commented on src/renderer/helpers/path.js
> +const SEREG = /(\.s[e]?(\d+)|(\d+)季|([零一二三四五六七八九十百千]+)季)/i;
目测好像都是`第01集`

2019-02-20 04:31 UTC, ipy commented on src/renderer/helpers/path.js
> +const SEREG = /(\.s[e]?(\d+)|(\d+)季|([零一二三四五六七八九十百千]+)季)/i;
![default](https://user-images.githubusercontent.com/2088040/53066542-52b4be00-350b-11e9-9b17-f5ddaf613a85.png)
只有这一个是 “01”，“集”都没有...说起来这种应该也是有不少的

2019-02-20 05:17 UTC, townmi commented on src/renderer/helpers/path.js
> +const SEREG = /(\.s[e]?(\d+)|(\d+)季|([零一二三四五六七八九十百千]+)季)/i;
`第`添加到条件里面去了

2019-02-20 05:18 UTC, townmi commented on src/renderer/helpers/path.js
> +const SEREG = /(\.s[e]?(\d+)|(\d+)季|([零一二三四五六七八九十百千]+)季)/i;
`.- \s` 都加到首位条件里面去了

2019-02-20 08:32 UTC, ipy requested changes

2019-02-20 08:32 UTC, ipy commented on src/renderer/helpers/path.js
> +      // $0 -> first offset (\d+)
一般 $0 表示整个匹配内容（这里的`content`），捕获组从 $1 开始
另外这里的正则最外层的捕获好像没什么必要？

2019-02-20 08:32 UTC, ipy commented on src/renderer/helpers/path.js
> +const EPREG = /(e[p]?(\d+)[.-\s]|第(\d+)集|第([零一二三四五六七八九十百千]+)集)/i;
ep 后面的字符为什么要限制呢？下面是一些例外的情况：
`[YYeTs][Taken][EP01][CN][DVDrip][640X352].rmvb`
`Greys.Anatomy.Season12.EP01_S-Files.mp4`

另外后面这个 `seasonXX` 不打算支持哈？

2019-02-20 08:32 UTC, ipy commented on test/unit/specs/helpers/path.spec.js
> +    ['美剧.EP01.x264-SVA.mp4', '天龙八部第一集.test.mp4', '天龙八部.第1集.mp4', ' 天龙八部第01集.mkv', '天龙八部第01集.mp4'].forEach((e) => {
后面两个用例基本一样可以删掉一个了

2019-02-21 02:34 UTC, townmi commented on src/renderer/helpers/path.js
> +const EPREG = /(e[p]?(\d+)[.-\s]|第(\d+)集|第([零一二三四五六七八九十百千]+)集)/i;
添加了命中率测试，上面两个案例都加入率选条件了

2019-02-21 02:34 UTC, townmi commented on src/renderer/helpers/path.js
> +      // $0 -> first offset (\d+)
嗯，修改了

2019-02-21 06:11 UTC, ipy approved these changes

2019-02-21 06:11 UTC, merged