Feat(subtitle) subtitle local storage
chiflix/splayerx pull request #490
Opened 2019-02-22 12:29 UTC by YvonTre

2019-02-23 09:54 UTC, ipy requested changes

2019-02-23 09:54 UTC, ipy commented on src/renderer/components/Subtitle/SubtitleLoader/index.js
> +        await promisify(loader.func.bind(this, ...this._getParams(toArray(loader.params))));
看了下 `_getParams` 方法里已经 `toArray` 过了。这里的 `promisify` 是否有必要？看了下好像都返回的是 Promise.

2019-02-23 09:54 UTC, ipy commented on src/renderer/components/Subtitle/SubtitleLoader/index.js
>      const loader = functionExtraction(this.loader.loader);
数据结构过于动态，很多类似`functionExtraction`这样的方法导致阅读困难，格式可以统一一下。See also: https://github.com/chiflix/splayerx/pull/474#pullrequestreview-204977075

2019-02-23 09:54 UTC, ipy commented on src/renderer/helpers/subtitle/storage.js
> +export async function updateSelectedSubtitleId(videoSrc, id) {
这样的方法目前是否有必要？直接调用`updateSubtitlePreference`貌似也没有很麻烦

2019-02-23 09:54 UTC, ipy commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +        if (!this.isInitial || (this.isInitial && clearOnline)) {
`if (!this.isInitial || clearOnline)` 应该就行了

2019-02-23 09:54 UTC, ipy commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +      return newLocalSubs;
可以考虑写成函数式，可能更清晰一点：
```
newLocalSubs
  .concat(storedSubs
    .filter(storedSub => !newLocalSubs.find(newSub => newSub.src === storedSub.src))
    .map(sub => ({
      src: sub.src,
      type: 'local',
    }))
  )
  .map(sub => ({
    ...sub,
    options: { ...sub.options, id: sub.id },
  }))
```

2019-02-23 09:54 UTC, ipy commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +      newEmbeddedSubs = newEmbeddedSubs instanceof Array ? newEmbeddedSubs : [newEmbeddedSubs];
可以用[`_.castArray`](https://lodash.com/docs/#castArray). 其他地方的 `toArray` 最好也改一下，这个名字很有歧义

2019-02-23 09:54 UTC, ipy commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +    async generateValidSubtitle(id) {
这两个方法好像没有引用？

2019-02-23 10:04 UTC, ipy commented
注释还是很单薄啊...

2019-02-23 18:43 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +      return newLocalSubs;
因为这里需要对newLocalSubs和storedSubs中的信息进行合并避免重复添加。
在newLocalSubs里面，sub.id是不存在的，因此要和storedSubs里面的同src字幕进行id的添加。

2019-02-23 18:50 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +      newEmbeddedSubs = newEmbeddedSubs instanceof Array ? newEmbeddedSubs : [newEmbeddedSubs];
改成`castArray`了

2019-02-23 18:53 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +        if (!this.isInitial || (this.isInitial && clearOnline)) {
改好了

2019-02-23 18:56 UTC, YvonTre commented on src/renderer/helpers/subtitle/storage.js
> +export async function updateSelectedSubtitleId(videoSrc, id) {
想的是能在这里处理一些找不到的情况，返回一些预设好的标准结果。

2019-02-23 19:00 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleLoader/index.js
>      const loader = functionExtraction(this.loader.loader);
就是不同的字幕对不同的信息获取方式都不太一样。。。想着全部写在`SubtitleLoader`里面就太多了。

2019-02-23 19:02 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleLoader/index.js
> +        await promisify(loader.func.bind(this, ...this._getParams(toArray(loader.params))));
`localNameLoader`使用的是普通的同步函数。或者可以把所有相关函数改成`Promise`。

2019-02-23 19:03 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +    async generateValidSubtitle(id) {
想着以后把SubtitleList提取出来之后就会有用处了。

2019-02-24 04:35 UTC, ipy commented on src/renderer/components/Subtitle/SubtitleLoader/index.js
> +        await promisify(loader.func.bind(this, ...this._getParams(toArray(loader.params))));
这里用了 await，普通变量应该也没关系的

2019-02-24 04:37 UTC, ipy commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +    async generateValidSubtitle(id) {
备注说明一下。多考虑考虑其他人（以及一个月后的自己）读代码的感受~

2019-02-24 05:45 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +      return newLocalSubs;
比如说
```javascript
const newLocalSubs = [{ src: '123', type: 'online', options: {}}];
const storedSubs = [{src: '123', id: 233}];
const rightSubs = [{ src: '123', type: 'online', options: { id: 233 }}];
const wrongSubs = newLocalSubs;
```

2019-02-24 08:22 UTC, ipy commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +      return newLocalSubs;
前面代码写得不对。不过这里主要是建议了一种编码风格，可以多考虑下代码是否可以写得更易读一些，函数式的风格是一个选项，而且 lodash 也提供了不少辅助方法
说起来似乎这么写就可以了：
```
_.values(_.mergeWith(
  _.keyBy(storedSubs.map(({src, id}) => ({ src, type: 'local', options: { id } })), 'src'),
  _.keyBy(newLocalSubs, 'src'),
))
```

2019-02-25 04:01 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +    async generateValidSubtitle(id) {
添加了注释

2019-02-25 04:02 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +      return newLocalSubs;
将所有类似的代码转成了函数式。

2019-02-25 04:14 UTC, ipy approved these changes

2019-02-25 06:54 UTC, merged