refactor(thumbnail): refactor thumbnail by api generatethumbnails
chiflix/splayerx pull request #499
Opened 2019-02-28 10:43 UTC by Pat1enceLos

- realize basic function for test

2019-03-02 13:29 UTC, ipy commented
![image](https://user-images.githubusercontent.com/2088040/53682307-7360ed00-3d2f-11e9-936a-73e0a1a03ad1.png)

2019-03-02 13:30 UTC, ipy commented
![thumbnail](https://user-images.githubusercontent.com/2088040/53682600-5548bc00-3d32-11e9-9b55-b3a47970adeb.jpg)
截图很模糊

2019-03-02 13:39 UTC, ipy requested changes

2019-03-02 13:39 UTC, ipy commented on src/renderer/components/PlayingView/ThumbnailDisplay.vue
> +      this.num = ['10', `${Math.ceil(num / 10)}`];
变量名含义不明，可以用 `{ cols, rows }` 之类的

2019-03-02 13:39 UTC, ipy commented on src/renderer/components/PlayingView/ThumbnailDisplay.vue
> +      const fileContent = await await getVideoInfoByMediaHash(this.mediaHash);
两个 `await`?

2019-03-02 13:39 UTC, ipy commented on src/renderer/components/PlayingView/ThumbnailDisplay.vue
> +    this.$bus.$on('generateThumbnails', async (num) => {
事件名其他地方都用的中划线风格，可以统一一下

2019-03-02 13:39 UTC, ipy commented on src/main/index.js
> +  ipcMain.on('generateThumbnails', (event, args) => {
需要有一个队列/去重的机制

2019-03-02 13:39 UTC, ipy commented on src/renderer/helpers/cacheFileStorage.js
> +const DEFAULT_DIRNAME = 'temp'; // 设定的应用缓存目录
temp 这个名字建议换一下

2019-03-02 13:39 UTC, ipy commented on src/renderer/helpers/cacheFileStorage.js
> +function mkdir(p) {
这里没什么特殊逻辑，可以直接用 `fs.promises`

2019-03-02 13:39 UTC, ipy commented on src/renderer/helpers/cacheFileStorage.js
> +        if (result instanceof Error) {
await 的 promise 被 reject 了会直接抛错，判断错误应该用 try catch

2019-03-02 13:39 UTC, ipy commented on src/renderer/helpers/cacheFileStorage.js
> +export async function generateThumbnailPathByMediaHash(key) {
这几个方法体大量重复，可以合并掉

2019-03-04 03:05 UTC, Pat1enceLos commented on src/main/index.js
> +  ipcMain.on('generateThumbnails', (event, args) => {
windows菜单的报错新提了一个pr，截图大小采用的是缩略图最大phase下的宽272px，如果一个一个去执行队列里面的任务，很有可能导致连续切换视频会一直没有缩略图，所以想的是每次执行完一个任务后再去执行队列里面最新加进来的任务，中间的全部舍弃掉

2019-03-06 04:02 UTC, townmi commented on src/renderer/helpers/cacheFileStorage.js
> +const DEFAULT_DIRNAME = 'temp'; // 设定的应用缓存目录
嗯，参考了notion的缓存目录

2019-03-06 04:04 UTC, townmi commented on src/renderer/helpers/cacheFileStorage.js
> +function mkdir(p) {
这个地方不太适合使用fspromise，fs原生的许多api，需要处理各类参数和err.code,mkdir和rmdir 都是使用的第三方库，比较方便。

2019-03-06 04:05 UTC, townmi commented on src/renderer/helpers/cacheFileStorage.js
> +        if (result instanceof Error) {
嗯，知道了，大意了

2019-03-06 04:07 UTC, townmi commented on src/renderer/helpers/cacheFileStorage.js
> +export async function generateThumbnailPathByMediaHash(key) {
合成一个私有函数，但是export出去的还是三个不用的方法，这里主要考虑防止文件名混乱，由内部控制文件名。

2019-03-06 04:19 UTC, ipy commented on src/main/index.js
> +      thumbnailQueue.shift();
队列的实现可以考虑考虑再优化下，按 @Pat1enceLos  的说法应该是要后进先出。先合并了

2019-03-06 04:19 UTC, ipy approved these changes

2019-03-06 04:20 UTC, merged