refactor(architecture): refactor project architecture
chiflix/splayerx pull request #624
Opened 2019-05-20 11:22 UTC by townmi

- [ ] subtitle module
- [ ] log module
- [ ] media module

2019-05-21 11:48 UTC, ymmuse commented on src/renderer/libs/file.ts
> +function checkPermission(path: string): Promise<boolean> {
设计为 checkPermission  那么就只是 check 访问权限，不需要再做更多（创建目录）。
另外，这个函数名修改成 checkPathExist 会更直观

2019-05-21 11:48 UTC, ymmuse commented on src/renderer/constants.js
> +
在constants.js文件顶部 可以 简要注释 介绍一下  该文件存放的常量都是 什么类型的 ，注意事项是什么。
比如：“ 在进行业务开发过程中如果需要定义常量 应该在此文件中进行声明定义。”

2019-05-21 11:48 UTC, ymmuse commented on src/renderer/libs/file.ts
> +export class CacheFile implements IFileStorable {
这里 应该把 CacheFile 从file.ts中抽出来，单独放到cachefile.ts文件中。
这样 file.ts就非常干净，并且是提供了公共文件操作的接口。里面也不会有IFileStorable这类无关的东西污染到

2019-05-21 11:48 UTC, ymmuse commented on src/renderer/services/media/index.ts
>  export interface IMediaStorable {
文件名改成IMediaStorable.ts会更直观

2019-05-21 11:48 UTC, ymmuse commented on src/renderer/services/media/thumbnailService.ts
> +   * @returns {Promise<string>}
这里最关键的 返回值信息说明 需要注释 ，因为它是API。

2019-05-21 11:48 UTC, ymmuse commented on src/renderer/services/media/thumbnailService.ts
>    async getImage(mediaHash: string): Promise<string | null> {
这个getImage接口移动到mediaStorageService下是否更合适？这样也减少了和ThumbnailService的交集

2019-05-21 11:48 UTC, ymmuse commented on src/renderer/services/storage/index.ts
>  export interface IFileStorable {
还是文件名，index.ts 改成IFileStorable.ts会更直观

2019-05-21 11:48 UTC, ymmuse commented on src/renderer/services/storage/mediaStorageService.ts
> +  private createDir(mediaHash: string): Promise<string> {
这里是业务逻辑访问，这个createDir太不直观，修改成 createVideoDir 会不会更贴合应用场景？

2019-05-21 11:48 UTC, ymmuse commented on src/renderer/services/storage/mediaStorageService.ts
> +  async getImage(mediaHash: string, tag: string): Promise<string | null> {
getImage 修改成 getVideoCoverStoragePath 会更直观

2019-05-21 11:48 UTC, ymmuse commented on src/renderer/services/storage/mediaStorageService.ts
> +  async generate(mediaHash: string, tag: string): Promise<string | null> {
同上， generate 改成 makeVideoCover

2019-05-22 02:25 UTC, townmi commented on src/renderer/containers/ThePreviewThumbnail.vue
> +      this.currentIndex = Math.abs(Math.floor(val / (this.duration / this.thumbnailCount)));
`currentTime`改变后，计算背景定位，这块逻辑，可以抽到接口，由service来实现，也方便unit测试,`backSize`也是的，命名可以规范化，`backPos` -> `backgroundPosition`.

2019-05-22 02:25 UTC, townmi commented on src/renderer/services/storage/mediaStorageService.ts
> +  async generate(mediaHash: string, tag: string): Promise<string | null> {
@ymmuse `generate` 这个API是有参数，是不是cover，由`tag`参数决定, 如果改的化，`generatePath`会更合适

2019-05-22 02:25 UTC, townmi commented on src/renderer/services/storage/mediaStorageService.ts
> +  private createDir(mediaHash: string): Promise<string> {
@ymmuse 我觉得还是换成 `createDirBy`，by什么由参数决定，好像swift就是这么规范的

2019-05-22 02:25 UTC, townmi commented on src/renderer/services/storage/index.ts
>  export interface IFileStorable {
@ymmuse storage模块不止一个接口，还需要定义indexDB的抽象接口，我是打算都放到`index.ts`，包括模块下的所有service, 都集中到`index.ts`

2019-05-22 02:25 UTC, townmi commented on src/renderer/services/media/thumbnailService.ts
>    async getImage(mediaHash: string): Promise<string | null> {
@ymmuse 这个`getImage` 是Thumbnail逻辑组件需要的API, 是组件抽象出来的业务逻辑

2019-05-22 02:25 UTC, townmi commented on src/renderer/services/media/index.ts
>  export interface IMediaStorable {
@ymmuse 这个同storage模块的想法一致，可以看下面的review

2019-05-22 02:25 UTC, townmi commented on src/renderer/libs/file.ts
> +export class CacheFile implements IFileStorable {
同意

2019-05-22 02:25 UTC, townmi commented on src/renderer/libs/file.ts
> +function checkPermission(path: string): Promise<boolean> {
同意

2019-05-22 02:25 UTC, townmi commented on src/renderer/constants.js
> +
同意

2019-05-23 00:28 UTC, ipy commented on .electron-vue/webpack.renderer.config.js
> +        test: /\.tsx$/,
是否把前面那条改成`/\.tsx?$/`就行了？

2019-05-23 00:28 UTC, ipy commented on src/renderer/constants.js
> +export const ELECTRON_CACHE_DIRNAME = 'userData'; // 用户数据路径
这样的注释方式不会体现在代码提示中，建议用 jsdoc 的方式写在上面

2019-05-23 02:20 UTC, townmi commented on .electron-vue/webpack.renderer.config.js
> +        test: /\.tsx$/,
同意

2019-05-23 02:21 UTC, townmi commented on src/renderer/constants.js
> +export const ELECTRON_CACHE_DIRNAME = 'userData'; // 用户数据路径
同意，

2019-05-23 02:48 UTC, ipy commented on src/renderer/services/storage/mediaStorageService.ts
> +export default new MediaStorageService(cacheFileInstance);
建议
```
 export default MediaStorageService; 
 export instance = new MediaStorageService(cacheFileInstance); 
```
文件名用 CamelCase 和默认导出一致，这样后面如果加容器的话改动较小

2019-05-23 03:10 UTC, townmi commented on src/renderer/services/storage/mediaStorageService.ts
> +export default new MediaStorageService(cacheFileInstance);
文件名使用大驼峰还是小驼峰，都可以，我是参考的vscode他们用的小驼峰，然后就是`export default` 我觉得 default 一个对象出去比较好，后面如果需要unit test, 我直接 那这个对象去测试，测试不会使用IOC容器吧

2019-05-24 02:53 UTC, ipy commented on src/renderer/services/storage/mediaStorageService.ts
> +export default new MediaStorageService(cacheFileInstance);
这文件名（尤其是接口文件）看着实在还是不太舒服。如果导出一个对象，用小驼峰可以说得过去，导出类和接口的话就显得不太协调了。
而且重要的是我们现有的命名都是大驼峰的
![image](https://user-images.githubusercontent.com/2088040/58299489-db484080-7e11-11e9-9faa-9740edee0cba.png)

2019-05-24 03:04 UTC, ipy commented on test/unit/specs/services/media/thumbnailService.spec.js
> +  const mediaStorageService = new MediaStorageService(cacheFile);
这里就像昨天说的，最好的方式是 mock 一个能够完全控制的 IMediaStorable 实例出来，这样对 ThumbnailService 的测试就不会受到 MediaStorageService 和 CacheFile 的影响。
这样`getThumbnailImage`的行为如果和预期不符，就可以清楚地知道是它本身的代码逻辑出了问题，而不用一层层去排查它的各种依赖，所以才叫“单元”测试。

2019-05-27 03:38 UTC, townmi commented on src/renderer/services/storage/mediaStorageService.ts
> +export default new MediaStorageService(cacheFileInstance);
文件名和export 都改了

2019-05-27 22:37 UTC, ipy requested changes

2019-05-27 22:37 UTC, ipy commented on src/renderer/interfaces/containers/iThumbnailRequest.ts
> +export interface IThumbnailRequest {
接口的文件名也改成大驼峰吧

2019-05-28 01:38 UTC, townmi commented on src/renderer/interfaces/containers/iThumbnailRequest.ts
> +export interface IThumbnailRequest {
👌

2019-05-28 02:44 UTC, ipy requested changes

2019-05-28 02:44 UTC, ipy commented on test/unit/specs/services/storage/mediaStorageService.spec.js
> +import CacheFile from '../../../../../src/renderer/libs/cacheFile';
* 测试文件的文件名跟被测文件也要保持一致
* 这里引用还是用的原来的文件名，在大小写敏感的文件系统下会找不到文件

2019-05-28 02:44 UTC, ipy commented on test/unit/specs/libs/cacheFile.spec.js
> +  it('createDirBy return true', async () => {
这个 description 太技术化了，并不能明确表明预期是什么。测试的语言应当从普通观众的角度出发，可以是类似`should successfully createDirBy`，`should return no result by readDirBy`这样的。

2019-05-28 02:44 UTC, ipy commented on test/unit/specs/libs/cacheFile.spec.js
> +    expect(JSON.stringify(result)).to.be.equal(JSON.stringify([]));
* 如果之前播放了测试视频导致生成了对应文件，是否会导致单元测试失败？
* 即使不考虑异常情况，`readDirBy`逻辑也有路径存在和不存在两个分支，没有覆盖全

2019-05-28 02:44 UTC, ipy commented on src/renderer/services/media/ThumbnailService.ts
> +const ROWS = 10;
命名反了的话就纠正过来吧

2019-05-28 02:44 UTC, ipy commented on src/renderer/interfaces/services/ICacheFileStorable.ts
> +  getPathBy(mediaHash: string): string
这边的方法命名风格个人感觉有点奇怪，会觉得语义是根据什么获取path，从而感觉参数应该是"mediaHash"这个类型而不是具体的哈希值。
建议用 `getPathByMediaHash` 这样的。

2019-05-28 02:44 UTC, ipy commented on test/unit/specs/services/media/thumbnailService.spec.js
> +      const result = await thumbnailService.getThumbnailImage(mediaHash);
`ipcRenderer` 应该也要 mock 掉，这个测试应该主要测试 `ipcRenderer.send` 被调用了。这个后面再想办法处理吧

2019-05-28 02:44 UTC, ipy commented on test/unit/specs/services/storage/mediaStorageService.spec.js
> +      const result = await mediaStorageService.readVideoInfo(mediaHash);
`readVideoInfo` 不应该返回空对象，read 不存在的视频信息的时候才应该返回空对象。这个信息要体现在测试描述里

2019-05-28 02:44 UTC, ipy commented on test/unit/specs/services/storage/mediaStorageService.spec.js
> +    it('readVideoInfo return {}', async () => {
描述与实际不符

2019-05-28 02:55 UTC, townmi commented on test/unit/specs/libs/cacheFile.spec.js
> +    expect(JSON.stringify(result)).to.be.equal(JSON.stringify([]));
1. 测试和播放不是同一个缓存目录，测试缓存是临时的目录回删除的
2. 不存在路径和路径存在但是没有内容返回同样的结果

2019-05-28 03:00 UTC, ipy commented on test/unit/specs/libs/cacheFile.spec.js
> +    expect(JSON.stringify(result)).to.be.equal(JSON.stringify([]));
这里是举个例子。单元测试是白盒测试，测试的是过程的正确性。不光要证明返回了这样的结果，更主要的是要证明*两种情况下都*返回了这样的结果

2019-05-28 03:17 UTC, townmi commented on src/renderer/interfaces/services/ICacheFileStorable.ts
> +  getPathBy(mediaHash: string): string
这个是参考的swift命名规范

2019-05-28 03:22 UTC, ipy commented on src/renderer/interfaces/services/ICacheFileStorable.ts
> +  getPathBy(mediaHash: string): string
按swift命名规范的话，这里应该是`getPath(byMediaHash)`...
![image](https://user-images.githubusercontent.com/2088040/58448522-e31e2280-813a-11e9-809b-ee26369cb90f.png)

2019-05-28 03:27 UTC, townmi commented on src/renderer/interfaces/services/ICacheFileStorable.ts
> +  getPathBy(mediaHash: string): string
不是介词提前么？

2019-05-28 03:32 UTC, ipy commented on src/renderer/interfaces/services/ICacheFileStorable.ts
> +  getPathBy(mediaHash: string): string
正常是体现在参数里，只有多个参数每个都一样的时候才提前到方法名里

2019-05-28 07:30 UTC, ipy commented on test/unit/specs/services/storage/mediaStorageService.spec.js
> +    it('should return no result by readVideoInfo', async () => {
这里应该要体现一下没数据时返回空对象而不是null吧

2019-05-28 07:37 UTC, townmi commented on test/unit/specs/services/storage/mediaStorageService.spec.js
> +    it('should return no result by readVideoInfo', async () => {
嗯，换了描述

2019-05-28 07:39 UTC, ipy approved these changes

2019-05-28 07:52 UTC, merged