refactor(VideoCanvas): refactor VideoCanvas components with Strip logic
chiflix/splayerx pull request #627
Opened 2019-06-03 08:00 UTC by townmi

- [x] refactor VideoCanvas Window logic
- [ ] refactor VideoCanvas Storage logic

2019-06-11 02:13 UTC, ipy requested changes

2019-06-11 02:13 UTC, ipy commented on src/renderer/components/PlayingView/BaseVideoPlayer.vue
> +      validator: (value:string) => [null, 'anonymous', 'user-credentials'].includes(value),
冒号后面应有空格。可以先不管，后面找个时间统一全局格式化一下

2019-06-11 02:13 UTC, ipy commented on src/renderer/libs/JStorage.ts
> +export default class JStorage implements IStorage {
`JStorage` 这个名字不太清晰，可以就叫`JsonStorage`

2019-06-11 02:13 UTC, ipy commented on src/renderer/interfaces/IDB.ts
> +/** MediaItem 全量结构
单行的注释写成单行
```
 /** MediaItem 全量结构 */
```

2019-06-11 02:13 UTC, ipy commented on src/renderer/services/window/WindowRectService.ts
> +  private calculateWindowSize(minSize: number[], maxSize: number[], videoSize: number[]): number[];
这两行方法定义的作用是？

2019-06-11 02:13 UTC, ipy commented on test/unit/specs/services/storage/PlayInfoStorageService.spec.js
> +  // it('should fail updateRecentPlayedBy with error data', async () => {
注释掉代码块的话写清楚下原因

2019-06-11 06:44 UTC, townmi commented on src/renderer/services/window/WindowRectService.ts
> +  private calculateWindowSize(minSize: number[], maxSize: number[], videoSize: number[]): number[];
`calculateWindowSize`是个重载函数

2019-06-11 13:14 UTC, ipy requested changes

2019-06-11 13:14 UTC, ipy commented on src/renderer/services/window/WindowRectService.ts
> + * @type number[]
用 ts 的话，类型可以自动推导，type 的注释就不必要了

2019-06-11 13:14 UTC, ipy commented on src/renderer/services/window/WindowRectService.ts
> +  private calculateWindowSize(minSize: number[], maxSize: number[], videoSize: number[]): number[];
这两个方法签名定义有必要吗，主方法用的可选参数，应该已经包含这两种情况了

2019-06-11 13:14 UTC, ipy commented on src/renderer/interfaces/IDB.ts
> +// MediaItem 全量结构
还是应该写成 `/** xxx */` 的形式，`//` 这种不会体现在代码提示里

2019-06-12 09:40 UTC, ipy approved these changes

2019-06-12 09:40 UTC, merged