refactor(vuex): remove vuex store from main
chiflix/splayerx pull request #630
Opened 2019-06-10 09:44 UTC by YvonTre

2019-06-10 23:23 UTC, ipy requested changes

2019-06-10 23:23 UTC, ipy commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +        } if (index <= 2) {
`if`应该换行（不止这一处）

2019-06-10 23:23 UTC, ipy commented on package.json
> +    "electron-rebuild": "^1.8.2",
版本号降了是因为？

2019-06-10 23:23 UTC, ipy commented on src/main/index.js
> +    mainWindow.webContents.send('mainCommit', 'isHiddenByBossKey', true);
`?.`去掉的话非空判断还是得有

2019-06-10 23:23 UTC, ipy commented on src/renderer/store/modules/Playlist.js
> +      // unnecessary 'else' after 'return'
这几段注释可以删掉
类似的一些调整原因可以写在 commit message 或者 pr 描述里

2019-06-11 05:52 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +        } if (index <= 2) {
我查了一下大概有32处，这个是`npm run lint:fix`自动fix成这样的。

2019-06-11 06:00 UTC, YvonTre commented on package.json
> +    "electron-rebuild": "^1.8.2",
可能是合并导致的，现在改成`^1.8.4`了。

2019-06-11 06:00 UTC, YvonTre commented on src/renderer/store/modules/Playlist.js
> +      // unnecessary 'else' after 'return'
OK

2019-06-11 06:01 UTC, YvonTre commented on src/renderer/components/Subtitle/SubtitleManager.vue
> +        } if (index <= 2) {
可以用正则改掉。

2019-06-11 13:41 UTC, ipy approved these changes

2019-06-11 13:41 UTC, merged