refactor(TheVideoController): trans to typescript
chiflix/splayerx pull request #631
Opened 2019-06-11 05:54 UTC by townmi

2019-06-11 13:39 UTC, ipy requested changes

2019-06-11 13:39 UTC, ipy commented on src/renderer/components/NotificationBubble.vue
> +  // @ts-ignore
这里 ts-ignore 的原因是？

2019-06-11 13:39 UTC, ipy commented on src/renderer/containers/TheProgressBar.vue
> +    handleDocumentMouseup(event:any) {
这里可以用 MouseEvent
下面的 event.path 是非标准属性，可以去掉

2019-06-11 13:39 UTC, ipy commented on src/renderer/components/PlayingView/NextVideo.vue
> +    onMetaLoaded(event:any) {
这里可以用`Event`，下面的`event.target`可以转换成`HTMLVideoElement`. 没有特殊需要尽量不要用`any`

2019-06-11 13:39 UTC, ipy commented on src/renderer/components/PlayingView/PlaylistControl.vue
> +    handleAnimation(anim:any) {
最新版(5.5.4)的`lottie-web`已经带类型定义了，可以升级一下

2019-06-12 03:46 UTC, townmi commented on src/renderer/components/NotificationBubble.vue
> +  // @ts-ignore
vue的问题吧，我看到说是没有type属性
```
Argument of type '{ name: string; type: string; components: { titlebar: { name: string; type: string; components: { Icon: { name: string; props: { type: { type: StringConstructor; required: boolean; }; effect: { type: StringConstructor; default: string; }; state: { ...; }; isFullScreen: { ...; }; }; computed: { ...; }; created(): voi...' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
  Object literal may only specify known properties, and 'type' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.Vetur(2345)
```

2019-06-12 14:14 UTC, ipy approved these changes

2019-06-12 14:14 UTC, merged