feat(traing): traing audio to subtitle
chiflix/splayerx pull request #642
Opened 2019-06-21 02:36 UTC by townmi

- [x] grab audio buffer send to server
- [ ] add UI components
- [ ] get trained subtitle data

2019-07-22 06:24 UTC, ipy requested changes

2019-07-22 06:24 UTC, ipy commented on src/renderer/services/media/AudioGrabService.ts
> +/*
这个文件同时在 main 和 renderer 进程引用了，不应该放在 renderer 目录里
感觉这两块逻辑可以拆开，用消息通信

2019-07-23 03:53 UTC, townmi commented on src/renderer/services/media/AudioGrabService.ts
> +/*
已经拆开了

2019-07-23 06:46 UTC, ipy requested changes

2019-07-23 06:46 UTC, ipy commented on src/main/helpers/AudioGrabService.js
> +/*
可以用 ts 的

2019-07-23 06:46 UTC, ipy commented on src/renderer/components/NotificationBubble.vue
> +    'translate-bubble': TranslateBubble,
统一用 CamelCase 吧

2019-07-23 06:46 UTC, ipy commented on src/renderer/components/PlayingView/TranslateBubble.vue
> +  data() {
这个有用嘛？

2019-07-23 07:52 UTC, ipy commented on src/renderer/main.ts
> +    store.$ga = this.$ga;
可以按这个来 https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/vuex.md

2019-07-26 08:52 UTC, ipy submitted a review, later dismissed

2019-07-26 09:33 UTC, ipy approved these changes

2019-07-26 10:03 UTC, merged