feat(package.json): add subtitle icns and ico
chiflix/splayerx pull request #653
Opened 2019-06-25 09:14 UTC by Pat1enceLos

2019-06-25 09:48 UTC, ipy requested changes
文档补充了

2019-06-27 02:54 UTC, ipy commented on src/renderer/main.ts
> +    this.$electron.ipcRenderer.on('open-video-by-subtitle', (event: any, args: any) => {
最好刚开始就把类型写好，后面再补会比较闹心

2019-06-27 02:54 UTC, ipy commented on src/main/index.js
> +        mainWindow.webContents.send('open-video-by-subtitle', { files: filesToOpen.concat(subsToOpen), onlySubtitle: !filesToOpen.length });
这里应该可以复用原来的'open-file'事件，可以改下参数格式。事件太多的话维护起来比较麻烦

建议找视频的操作在主线程里完成，这样就不用加新事件了。而且找不到任何视频的时候应该要打开 LandingView 而不是 PlayingView

2019-06-27 09:35 UTC, ipy commented on scripts/masbuild.sh
> +npm_config_platform=mas npm i @chiflix/electron@$ELECTRON_VERSION
这个需要提交么

2019-06-27 09:54 UTC, Pat1enceLos commented on scripts/masbuild.sh
> +npm_config_platform=mas npm i @chiflix/electron@$ELECTRON_VERSION
测试的时候删的，加回来了

2019-06-28 00:33 UTC, ipy commented
* 同文件夹下的字幕文件也被当成视频加入了播放列表
![image](https://user-images.githubusercontent.com/2088040/60309169-0b3db300-997f-11e9-9655-ba028ece9eef.png)
* Windows 正在播放时，打开其他文件没有反应

2019-07-05 07:49 UTC, ipy approved these changes

2019-07-05 07:49 UTC, merged