feat(appx): window store tile setup
chiflix/splayerx pull request #696
Opened 2019-07-04 09:20 UTC by YuRiJinX

2019-07-04 15:31 UTC, ipy commented
![image](https://user-images.githubusercontent.com/2088040/60677335-d4522a80-9eb3-11e9-9f72-20c309e75371.png)

2019-07-05 05:36 UTC, YuRiJinX commented
@ipy privacy bubble已经ok了

2019-07-05 06:37 UTC, ipy commented on src/renderer/components/PlayingView/MASPrivacyConfirmBubble.vue
> +  background-image: radial-gradient(
这个样式每个地方有区别嘛？重复超过三次可以考虑拎出来了

2019-07-05 07:21 UTC, ipy requested changes

2019-07-05 07:21 UTC, ipy commented on src/renderer/css/style.scss
> +.fallback {
建议叫 .backdrop-fallback，说不定之后会有其他的 fallback...

2019-07-05 07:49 UTC, ipy approved these changes

2019-07-05 07:49 UTC, merged