fix(typo): fix old subtitle interfaces
chiflix/splayerx pull request #929
Opened 2019-09-04 11:02 UTC by YvonTre

Fix SubtitleControlListItem and IEmbeddedOrigin.

2019-09-06 03:22 UTC, ipy requested changes

2019-09-06 03:22 UTC, ipy commented on src/renderer/constants.js
> +const app = electron.app || electron.remote.app;
原则上 render 目录里的文件应该只在 render 进程引用，没有必要判断 electron.app

2019-09-06 03:22 UTC, ipy commented on src/renderer/constants.js
> +export const SUBTITLE_REAL_DIRNAME = join(
建议叫 SUBTITLE_FULL_DIRNAME, REAL 对应的概念是 FAKE...

2019-09-06 03:22 UTC, ipy commented on src/renderer/interfaces/ISubtitle.ts
> +  displaySource: IOrigin;
这些接口和属性都加一下注释说明

2019-09-06 03:22 UTC, ipy commented on src/renderer/libs/TimeSegments.ts
> +    return typeof num === 'number' && Number.isFinite(num) && !Number.isNaN(num) && num >= 0;
valid number 为什么要 >= 0?

2019-09-06 04:09 UTC, ipy commented on src/main/helpers/mediaTasksPlugin.ts
> +    if (streamSubtitlesMap) {
什么情况下 streamSubtitlesMap 会没有？

2019-09-06 04:09 UTC, ipy commented on src/main/helpers/mediaTasksPlugin.ts
> +            if (error || !data) reply(event, 'subtitle-metadata-reply', new Error(error));
没 error 没 data 的时候 error 可以给个默认的文本

2019-09-06 04:09 UTC, ipy commented on src/main/helpers/mediaTasksPlugin.ts
> +            } else if (error) reply(event, 'subtitle-cache-reply', new Error(error));
这里的 if else 建议都加上花括号，可读性会强一点
逻辑非常简单，没有其他分支的情况可以不加

2019-09-06 04:09 UTC, ipy commented on src/main/helpers/mediaTasksPlugin.ts
> +  ipcMain.on('subtitle-cache-request', async (event: Event, videoPath: string, streamIndex: number) => {
为什么叫 subtitle-cache-request 呢

2019-09-06 04:09 UTC, ipy commented on src/renderer/libs/TimeSegments.ts
> +  private checkWithIndex(time: number) {
注释~

2019-09-06 04:21 UTC, YvonTre commented on src/main/helpers/mediaTasksPlugin.ts
> +    if (streamSubtitlesMap) {
这个纯粹是为了TypeScript的类型写的，不写这个`if`TypeScript会说这个可能为`undefined`。

2019-09-06 04:22 UTC, YvonTre commented on src/main/helpers/mediaTasksPlugin.ts
> +  ipcMain.on('subtitle-cache-request', async (event: Event, videoPath: string, streamIndex: number) => {
因为这个请求是为了缓存字幕的，和为了获取字幕片段的不一样。
也可以写成像渲染进程的`sequential`和`random`。

2019-09-06 04:24 UTC, YvonTre commented on src/main/helpers/mediaTasksPlugin.ts
> +            if (error || !data) reply(event, 'subtitle-metadata-reply', new Error(error));
OK.

2019-09-06 04:24 UTC, YvonTre commented on src/main/helpers/mediaTasksPlugin.ts
> +            } else if (error) reply(event, 'subtitle-cache-reply', new Error(error));
OK.

2019-09-06 04:28 UTC, YvonTre commented on src/renderer/constants.js
> +const app = electron.app || electron.remote.app;
OK.

2019-09-06 04:28 UTC, YvonTre commented on src/renderer/constants.js
> +export const SUBTITLE_REAL_DIRNAME = join(
OK.

2019-09-06 04:55 UTC, YvonTre commented on src/renderer/interfaces/ISubtitle.ts
> +  displaySource: IOrigin;
OK.

2019-09-06 04:56 UTC, YvonTre commented on src/renderer/libs/TimeSegments.ts
> +    return typeof num === 'number' && Number.isFinite(num) && !Number.isNaN(num) && num >= 0;
OK.

2019-09-06 05:11 UTC, YvonTre commented on src/renderer/libs/TimeSegments.ts
> +  private checkWithIndex(time: number) {
OK.
这个部分注释当作测试来写了，写了一些用例。

2019-09-06 06:26 UTC, ipy commented
retest this please

2019-09-09 01:26 UTC, ipy commented on src/renderer/libs/TimeSegments.ts
> +  private checkWithIndex(time: number) {
测试大部分情况下只能体现 how，不能体现 what 和 **why**, 不能完全替代注释

2019-09-09 01:27 UTC, ipy commented on src/renderer/services/storage/subtitle/db.ts
>  interface IDataDBV3 extends DBSchema {
之前版本的定义留着有用么？

2019-09-09 01:44 UTC, ipy commented
<img width="816" alt="图片" src="https://user-images.githubusercontent.com/2088040/64498273-5dd40d80-d2e6-11e9-9569-f1360ec7f369.png">

2019-09-09 02:06 UTC, YvonTre commented on src/renderer/services/storage/subtitle/db.ts
>  interface IDataDBV3 extends DBSchema {
比较直接的用处是在升级数据库函数中，可以有类型检查。
还有一个可能的用处是，万一数据库出错，可以对照原来的版本看（也可以通过git记录来看）。

2019-09-09 02:24 UTC, ipy requested changes

2019-09-09 02:24 UTC, ipy commented on src/renderer/services/storage/subtitle/db.ts
>                db.createObjectStore('subtitles', { keyPath: 'hash' });
create 写在外面了，这里可以删掉

2019-09-09 02:24 UTC, ipy commented on src/renderer/services/storage/subtitle/db.ts
>  interface IDataDBV3 extends DBSchema {
现在没有吧，可以删掉。对照的话看 git 记录

2019-09-09 02:24 UTC, ipy commented on src/renderer/services/storage/subtitle/db.ts
> +      this.db = await openDB<IDataDBV5>(
没清库重装老版本的时候打开新版数据库会报错，最好想办法处理一下

2019-09-09 02:41 UTC, YvonTre commented on src/renderer/services/storage/subtitle/db.ts
>                db.createObjectStore('subtitles', { keyPath: 'hash' });
这个是旧的记录，新的里面已经没有这两行了。

2019-09-09 02:54 UTC, YvonTre commented on src/renderer/services/storage/subtitle/db.ts
> +      this.db = await openDB<IDataDBV5>(
- [Indexed Database API 2.0 - Opening a database](https://www.w3.org/TR/IndexedDB/#opening)

  > 7. If db’s version is greater than version, return a newly created "VersionError" DOMException and abort these steps.

- 在高版本上打开低版本数据库一定会报错，可以考虑直接删除重建数据库升级到相应的低版本。

2019-09-09 05:52 UTC, ipy approved these changes

2019-09-09 06:22 UTC, merged