fix(loop & playlist): fix loop issues & add new sort algorithm
chiflix/splayerx pull request #957
Opened 2019-09-16 09:36 UTC by YuRiJinX

2019-09-16 10:03 UTC, ipy requested changes

2019-09-16 10:03 UTC, ipy commented on src/renderer/helpers/sort.ts
> +  const numbersInA = videoFile1.match(/\d+/g);
这个比较还是有点问题,举个例子 第1季第10集 就大于 第2季第1集 了。可以每一段分别比较
另外现在的测试用例不能说明问题，还是要极端一点

2019-09-17 10:54 UTC, ipy commented on src/renderer/helpers/index.js
> +      videoFiles.sort(sortVideoFile);
需要 sort 两遍么

2019-09-17 10:56 UTC, YuRiJinX commented on src/renderer/helpers/index.js
> +      videoFiles.sort(sortVideoFile);
下面是这么写的，先把纯字符串的排完再在这个基础上排有数字的。。

2019-09-17 11:00 UTC, ipy commented on src/renderer/helpers/index.js
> +      videoFiles.sort(sortVideoFile);
前面一次应该是没什么用的

2019-09-17 11:02 UTC, ipy approved these changes

2019-09-17 11:03 UTC, merged