implemented updater. can't work in win CI using electron beta3
chiflix/splayerx pull request #96
Opened 2018-07-24 12:11 UTC by lycbel2

目前windows下不支持electron3.0.0 beta3 的update 在checking时会报ssl error
需要配置 CI 里的 GH_TOKEN env
App.vue 里的 UpdaterProgressIndicator 为了测试用以后要删掉

2018-07-24 14:08 UTC, ymmuse commented
当前3.0还不稳定，针对基于3.0beta的SPlayerX的代码增加或变动，很有可能也会随稳定版发布而有所影响。所以我认为有必要新开一个branch develop_v3.x来方便应对稳定版的调整兼容工作。

2018-07-24 15:17 UTC, tomasen requested changes

2018-07-24 15:17 UTC, tomasen commented on appveyor.yml
> +environment:
请看 https://ci.appveyor.com/project/tomasen/splayerx/build/1.0.389
显示此处配置错误
`Error parsing appveyor.yml: Invalid setting or section: nvironment (Line: 47, Column: 1)`
看看是否缩进或位置问题

2018-07-25 01:16 UTC, lycbel2 commented on appveyor.yml
> +environment:
environment 少copy了一个e，昨天第二个commit ‘fix environment typo in appveyor.yml’ 改过来了。

2018-07-25 02:23 UTC, tomasen approved these changes

2018-07-25 02:46 UTC, closed without merging